version: "3.7"
  planning-api:
    image: planning-api
    container_name: planning-ap
    restart: on-failure
    ports:
      - 8080:8080
      - 5005:5005
    build:
      context: "./"
      dockerfile: "Dockerfile"
    environment:
      ADDITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx256m -Xms128m -XX:MaxMetaspaceSize=128m

